#!/usr/bin/env bash
###############################################################################
# pipeline.sh
# -----------
# A concise end-to-end workflow that
#   1) filters raw segmentation masks,
#   2) extracts Vision-Transformer patch embeddings for every accepted nucleus,
#   3) clusters the embeddings and produces publication-ready overlays.
#
# Author : Christos Botos – Mahfouz Lab
# Created: 16-Jun-2025
###############################################################################
# Exit on the first error, on undefined variables, and propagate errors
# through pipes. This makes the pipeline fail fast and loud.
set -euo pipefail

#######################################
# User-editable parameters.
#######################################
# Path to the raw microscopy image (e.g. DAPI channel).
IMAGE="img/IRI_regist_cropped.tif"

# Path to the unfiltered segmentation masks generated by Cellpose, Stardist, etc.
RAW_MASKS="segmentation_masks.npy"

# Desired ViT crop sizes in pixels. Supply one or many numbers separated by spaces.
PATCH_SIZES=(16 32 64)

# Initial guess for the number of K-Means clusters. It can be overridden automatically.
K_INIT=10
AUTO_K="silhouette"           # Choose “silhouette”, “dbi” or “none”.

# Patch-extraction batch size (higher is faster but needs more GPU memory).
BATCH_SIZE=16384

# Visualisation box in *fractional* image coordinates: ymin ymax xmin xmax.
# Keep 0 1 0 1 to process the full frame or tighten it to zoom.
VIZ_BOX=(0.5 0.51 0.66 0.67)

# Filtering thresholds. Adjust to your dataset or keep the generous defaults.
MIN_PIXELS=20       ; MAX_PIXELS=570
MIN_CIRC=0.63       ; MAX_CIRC=1.00
MIN_SOL=0.80        ; MAX_SOL=1.00
MIN_ECC=0.00        ; MAX_ECC=0.98
MIN_AR=0.50         ; MAX_AR=3.20
MIN_HOLE=0.00       ; MAX_HOLE=0.001

#######################################
# Derived paths – change only if needed.
#######################################
BASE=$(basename "${IMAGE%.*}")              # e.g. IRI_regist_cropped
FILTER_DIR="test_fifth_run"               # All outputs from filter_masks.py.
PATCH_DIR="test_fifth_run"             # All patch CSVs/NPYs live here.
CLUSTER_DIR="test_fifth_run"         # Final clustering artefacts.

###############################################################################
# 1. Filter segmentation masks.
###############################################################################
echo "➤ Filtering masks …"
python filter_masks_memopt.py \
    --input  "${RAW_MASKS}" \
    --results-dir "${FILTER_DIR}" \
    --output-prefix "filtered_" \
    --min-pixels       "${MIN_PIXELS}"       --max-pixels       "${MAX_PIXELS}" \
    --min-circularity  "${MIN_CIRC}"         --max-circularity  "${MAX_CIRC}" \
    --min-solidity     "${MIN_SOL}"          --max-solidity     "${MAX_SOL}" \
    --min-eccentricity "${MIN_ECC}"          --max-eccentricity "${MAX_ECC}" \
    --min-aspect-ratio "${MIN_AR}"           --max-aspect-ratio "${MAX_AR}"  \
    --min-hole-fraction "${MIN_HOLE}"        --max-hole-fraction "${MAX_HOLE}" \
    --summary-csv \
    --raw-image "${IMAGE}" \
    --overlay

###############################################################################
# 2. Extract ViT patch embeddings for every *passed* nucleus.
###############################################################################
echo "➤ Extracting Vision-Transformer patch embeddings …"
# Compose the list of --patch_sizes arguments.
PATCH_SIZE_ARGS=()
for S in "${PATCH_SIZES[@]}"; do PATCH_SIZE_ARGS+=( "$S" ); done

python segmentation_mask_dynamic_patches_vit.py \
    --image "${IMAGE}" \
    --mask  "${FILTER_DIR}/filtered_passed_labels.npy" \
    --label_map "${RAW_MASKS}" \
    --output "${PATCH_DIR}" \
    --patch_sizes "${PATCH_SIZE_ARGS[@]}" \
    --batch_size "${BATCH_SIZE}" \
    --model_name "facebook/dino-vits16" \
    --viz_crop_region "${VIZ_BOX[@]}"

###############################################################################
# 3. Cluster the embeddings and overlay results on the raw image.
###############################################################################
echo "➤ Clustering patch embeddings …"
python cluster_vit_patches.py \
    --image   "${IMAGE}" \
    --mask    "${FILTER_DIR}/filtered_passed_masks.npy" \
    --coords  "${PATCH_DIR}/coords_${BASE}.csv" \
    --features "${PATCH_DIR}/features_${BASE}.csv" \
    --clusters "${K_INIT}" \
    --auto-k   "${AUTO_K}" \
    --outdir   "${CLUSTER_DIR}" \
    --region   "${VIZ_BOX[@]}" \
    --log      "clustering.log"

echo "✓ Pipeline completed successfully."
